// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: protos/parking_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ParkingService_SearchGarages_FullMethodName      = "/parking.ParkingService/SearchGarages"
	ParkingService_GetGarage_FullMethodName          = "/parking.ParkingService/GetGarage"
	ParkingService_CreateReservation_FullMethodName  = "/parking.ParkingService/CreateReservation"
	ParkingService_ListReservations_FullMethodName   = "/parking.ParkingService/ListReservations"
	ParkingService_CancelReservation_FullMethodName  = "/parking.ParkingService/CancelReservation"
	ParkingService_RecordVehicleEntry_FullMethodName = "/parking.ParkingService/RecordVehicleEntry"
	ParkingService_RecordVehicleExit_FullMethodName  = "/parking.ParkingService/RecordVehicleExit"
	ParkingService_GetActiveVehicles_FullMethodName  = "/parking.ParkingService/GetActiveVehicles"
	ParkingService_GetVehicleEntry_FullMethodName    = "/parking.ParkingService/GetVehicleEntry"
)

// ParkingServiceClient is the client API for ParkingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ParkingServiceClient interface {
	// Busca de Garagens
	SearchGarages(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	GetGarage(ctx context.Context, in *GetGarageRequest, opts ...grpc.CallOption) (*Garage, error)
	// Sistema de Reservas
	CreateReservation(ctx context.Context, in *CreateReservationRequest, opts ...grpc.CallOption) (*Reservation, error)
	ListReservations(ctx context.Context, in *ListReservationsRequest, opts ...grpc.CallOption) (*ListReservationsResponse, error)
	CancelReservation(ctx context.Context, in *CancelReservationRequest, opts ...grpc.CallOption) (*CancelReservationResponse, error)
	// Sistema de Entrada/Saída (Latência Crítica - B+Tree Local)
	RecordVehicleEntry(ctx context.Context, in *VehicleEntryRequest, opts ...grpc.CallOption) (*VehicleEntryResponse, error)
	RecordVehicleExit(ctx context.Context, in *VehicleExitRequest, opts ...grpc.CallOption) (*VehicleExitResponse, error)
	GetActiveVehicles(ctx context.Context, in *GetActiveVehiclesRequest, opts ...grpc.CallOption) (*GetActiveVehiclesResponse, error)
	GetVehicleEntry(ctx context.Context, in *GetVehicleEntryRequest, opts ...grpc.CallOption) (*VehicleEntry, error)
}

type parkingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewParkingServiceClient(cc grpc.ClientConnInterface) ParkingServiceClient {
	return &parkingServiceClient{cc}
}

func (c *parkingServiceClient) SearchGarages(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, ParkingService_SearchGarages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) GetGarage(ctx context.Context, in *GetGarageRequest, opts ...grpc.CallOption) (*Garage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Garage)
	err := c.cc.Invoke(ctx, ParkingService_GetGarage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) CreateReservation(ctx context.Context, in *CreateReservationRequest, opts ...grpc.CallOption) (*Reservation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Reservation)
	err := c.cc.Invoke(ctx, ParkingService_CreateReservation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) ListReservations(ctx context.Context, in *ListReservationsRequest, opts ...grpc.CallOption) (*ListReservationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReservationsResponse)
	err := c.cc.Invoke(ctx, ParkingService_ListReservations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) CancelReservation(ctx context.Context, in *CancelReservationRequest, opts ...grpc.CallOption) (*CancelReservationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelReservationResponse)
	err := c.cc.Invoke(ctx, ParkingService_CancelReservation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) RecordVehicleEntry(ctx context.Context, in *VehicleEntryRequest, opts ...grpc.CallOption) (*VehicleEntryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VehicleEntryResponse)
	err := c.cc.Invoke(ctx, ParkingService_RecordVehicleEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) RecordVehicleExit(ctx context.Context, in *VehicleExitRequest, opts ...grpc.CallOption) (*VehicleExitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VehicleExitResponse)
	err := c.cc.Invoke(ctx, ParkingService_RecordVehicleExit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) GetActiveVehicles(ctx context.Context, in *GetActiveVehiclesRequest, opts ...grpc.CallOption) (*GetActiveVehiclesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActiveVehiclesResponse)
	err := c.cc.Invoke(ctx, ParkingService_GetActiveVehicles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) GetVehicleEntry(ctx context.Context, in *GetVehicleEntryRequest, opts ...grpc.CallOption) (*VehicleEntry, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VehicleEntry)
	err := c.cc.Invoke(ctx, ParkingService_GetVehicleEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParkingServiceServer is the server API for ParkingService service.
// All implementations must embed UnimplementedParkingServiceServer
// for forward compatibility.
type ParkingServiceServer interface {
	// Busca de Garagens
	SearchGarages(context.Context, *SearchRequest) (*SearchResponse, error)
	GetGarage(context.Context, *GetGarageRequest) (*Garage, error)
	// Sistema de Reservas
	CreateReservation(context.Context, *CreateReservationRequest) (*Reservation, error)
	ListReservations(context.Context, *ListReservationsRequest) (*ListReservationsResponse, error)
	CancelReservation(context.Context, *CancelReservationRequest) (*CancelReservationResponse, error)
	// Sistema de Entrada/Saída (Latência Crítica - B+Tree Local)
	RecordVehicleEntry(context.Context, *VehicleEntryRequest) (*VehicleEntryResponse, error)
	RecordVehicleExit(context.Context, *VehicleExitRequest) (*VehicleExitResponse, error)
	GetActiveVehicles(context.Context, *GetActiveVehiclesRequest) (*GetActiveVehiclesResponse, error)
	GetVehicleEntry(context.Context, *GetVehicleEntryRequest) (*VehicleEntry, error)
	mustEmbedUnimplementedParkingServiceServer()
}

// UnimplementedParkingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedParkingServiceServer struct{}

func (UnimplementedParkingServiceServer) SearchGarages(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchGarages not implemented")
}
func (UnimplementedParkingServiceServer) GetGarage(context.Context, *GetGarageRequest) (*Garage, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGarage not implemented")
}
func (UnimplementedParkingServiceServer) CreateReservation(context.Context, *CreateReservationRequest) (*Reservation, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateReservation not implemented")
}
func (UnimplementedParkingServiceServer) ListReservations(context.Context, *ListReservationsRequest) (*ListReservationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListReservations not implemented")
}
func (UnimplementedParkingServiceServer) CancelReservation(context.Context, *CancelReservationRequest) (*CancelReservationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelReservation not implemented")
}
func (UnimplementedParkingServiceServer) RecordVehicleEntry(context.Context, *VehicleEntryRequest) (*VehicleEntryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordVehicleEntry not implemented")
}
func (UnimplementedParkingServiceServer) RecordVehicleExit(context.Context, *VehicleExitRequest) (*VehicleExitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordVehicleExit not implemented")
}
func (UnimplementedParkingServiceServer) GetActiveVehicles(context.Context, *GetActiveVehiclesRequest) (*GetActiveVehiclesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActiveVehicles not implemented")
}
func (UnimplementedParkingServiceServer) GetVehicleEntry(context.Context, *GetVehicleEntryRequest) (*VehicleEntry, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVehicleEntry not implemented")
}
func (UnimplementedParkingServiceServer) mustEmbedUnimplementedParkingServiceServer() {}
func (UnimplementedParkingServiceServer) testEmbeddedByValue()                        {}

// UnsafeParkingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ParkingServiceServer will
// result in compilation errors.
type UnsafeParkingServiceServer interface {
	mustEmbedUnimplementedParkingServiceServer()
}

func RegisterParkingServiceServer(s grpc.ServiceRegistrar, srv ParkingServiceServer) {
	// If the following call panics, it indicates UnimplementedParkingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ParkingService_ServiceDesc, srv)
}

func _ParkingService_SearchGarages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).SearchGarages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParkingService_SearchGarages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).SearchGarages(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_GetGarage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGarageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).GetGarage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParkingService_GetGarage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).GetGarage(ctx, req.(*GetGarageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_CreateReservation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).CreateReservation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParkingService_CreateReservation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).CreateReservation(ctx, req.(*CreateReservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_ListReservations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReservationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).ListReservations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParkingService_ListReservations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).ListReservations(ctx, req.(*ListReservationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_CancelReservation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelReservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).CancelReservation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParkingService_CancelReservation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).CancelReservation(ctx, req.(*CancelReservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_RecordVehicleEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VehicleEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).RecordVehicleEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParkingService_RecordVehicleEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).RecordVehicleEntry(ctx, req.(*VehicleEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_RecordVehicleExit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VehicleExitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).RecordVehicleExit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParkingService_RecordVehicleExit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).RecordVehicleExit(ctx, req.(*VehicleExitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_GetActiveVehicles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveVehiclesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).GetActiveVehicles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParkingService_GetActiveVehicles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).GetActiveVehicles(ctx, req.(*GetActiveVehiclesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_GetVehicleEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVehicleEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).GetVehicleEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParkingService_GetVehicleEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).GetVehicleEntry(ctx, req.(*GetVehicleEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ParkingService_ServiceDesc is the grpc.ServiceDesc for ParkingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ParkingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "parking.ParkingService",
	HandlerType: (*ParkingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchGarages",
			Handler:    _ParkingService_SearchGarages_Handler,
		},
		{
			MethodName: "GetGarage",
			Handler:    _ParkingService_GetGarage_Handler,
		},
		{
			MethodName: "CreateReservation",
			Handler:    _ParkingService_CreateReservation_Handler,
		},
		{
			MethodName: "ListReservations",
			Handler:    _ParkingService_ListReservations_Handler,
		},
		{
			MethodName: "CancelReservation",
			Handler:    _ParkingService_CancelReservation_Handler,
		},
		{
			MethodName: "RecordVehicleEntry",
			Handler:    _ParkingService_RecordVehicleEntry_Handler,
		},
		{
			MethodName: "RecordVehicleExit",
			Handler:    _ParkingService_RecordVehicleExit_Handler,
		},
		{
			MethodName: "GetActiveVehicles",
			Handler:    _ParkingService_GetActiveVehicles_Handler,
		},
		{
			MethodName: "GetVehicleEntry",
			Handler:    _ParkingService_GetVehicleEntry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/parking_service.proto",
}
