// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: protos/parking_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReservationStatus int32

const (
	ReservationStatus_RESERVATION_STATUS_UNSPECIFIED ReservationStatus = 0
	ReservationStatus_PENDING                        ReservationStatus = 1
	ReservationStatus_ACTIVE                         ReservationStatus = 2
	ReservationStatus_COMPLETED                      ReservationStatus = 3
	ReservationStatus_CANCELLED                      ReservationStatus = 4
)

// Enum value maps for ReservationStatus.
var (
	ReservationStatus_name = map[int32]string{
		0: "RESERVATION_STATUS_UNSPECIFIED",
		1: "PENDING",
		2: "ACTIVE",
		3: "COMPLETED",
		4: "CANCELLED",
	}
	ReservationStatus_value = map[string]int32{
		"RESERVATION_STATUS_UNSPECIFIED": 0,
		"PENDING":                        1,
		"ACTIVE":                         2,
		"COMPLETED":                      3,
		"CANCELLED":                      4,
	}
)

func (x ReservationStatus) Enum() *ReservationStatus {
	p := new(ReservationStatus)
	*p = x
	return p
}

func (x ReservationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReservationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_parking_service_proto_enumTypes[0].Descriptor()
}

func (ReservationStatus) Type() protoreflect.EnumType {
	return &file_protos_parking_service_proto_enumTypes[0]
}

func (x ReservationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReservationStatus.Descriptor instead.
func (ReservationStatus) EnumDescriptor() ([]byte, []int) {
	return file_protos_parking_service_proto_rawDescGZIP(), []int{0}
}

type VehicleStatus int32

const (
	VehicleStatus_VEHICLE_STATUS_UNSPECIFIED VehicleStatus = 0
	VehicleStatus_PARKED                     VehicleStatus = 1 // Estacionado (ativo)
	VehicleStatus_EXITED                     VehicleStatus = 2 // Saiu (finalizado)
)

// Enum value maps for VehicleStatus.
var (
	VehicleStatus_name = map[int32]string{
		0: "VEHICLE_STATUS_UNSPECIFIED",
		1: "PARKED",
		2: "EXITED",
	}
	VehicleStatus_value = map[string]int32{
		"VEHICLE_STATUS_UNSPECIFIED": 0,
		"PARKED":                     1,
		"EXITED":                     2,
	}
)

func (x VehicleStatus) Enum() *VehicleStatus {
	p := new(VehicleStatus)
	*p = x
	return p
}

func (x VehicleStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VehicleStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_parking_service_proto_enumTypes[1].Descriptor()
}

func (VehicleStatus) Type() protoreflect.EnumType {
	return &file_protos_parking_service_proto_enumTypes[1]
}

func (x VehicleStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VehicleStatus.Descriptor instead.
func (VehicleStatus) EnumDescriptor() ([]byte, []int) {
	return file_protos_parking_service_proto_rawDescGZIP(), []int{1}
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	RadiusMeters  int32                  `protobuf:"varint,3,opt,name=radius_meters,json=radiusMeters,proto3" json:"radius_meters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_protos_parking_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_parking_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_protos_parking_service_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *SearchRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *SearchRequest) GetRadiusMeters() int32 {
	if x != nil {
		return x.RadiusMeters
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Garages       []*Garage              `protobuf:"bytes,1,rep,name=garages,proto3" json:"garages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_protos_parking_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_parking_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_protos_parking_service_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResponse) GetGarages() []*Garage {
	if x != nil {
		return x.Garages
	}
	return nil
}

type GetGarageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GarageId      string                 `protobuf:"bytes,1,opt,name=garage_id,json=garageId,proto3" json:"garage_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGarageRequest) Reset() {
	*x = GetGarageRequest{}
	mi := &file_protos_parking_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGarageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGarageRequest) ProtoMessage() {}

func (x *GetGarageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_parking_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGarageRequest.ProtoReflect.Descriptor instead.
func (*GetGarageRequest) Descriptor() ([]byte, []int) {
	return file_protos_parking_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetGarageRequest) GetGarageId() string {
	if x != nil {
		return x.GarageId
	}
	return ""
}

type Garage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BasePrice      float64                `protobuf:"fixed64,3,opt,name=base_price,json=basePrice,proto3" json:"base_price,omitempty"`
	Latitude       float64                `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude      float64                `protobuf:"fixed64,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	ImageUrl       string                 `protobuf:"bytes,6,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Campaigns      []*Campaign            `protobuf:"bytes,7,rep,name=campaigns,proto3" json:"campaigns,omitempty"`
	Address        string                 `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	Phone          string                 `protobuf:"bytes,9,opt,name=phone,proto3" json:"phone,omitempty"`
	TotalSpots     int32                  `protobuf:"varint,10,opt,name=total_spots,json=totalSpots,proto3" json:"total_spots,omitempty"`
	AvailableSpots int32                  `protobuf:"varint,11,opt,name=available_spots,json=availableSpots,proto3" json:"available_spots,omitempty"`
	Amenities      []string               `protobuf:"bytes,12,rep,name=amenities,proto3" json:"amenities,omitempty"` // WiFi, EV Charging, etc.
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Garage) Reset() {
	*x = Garage{}
	mi := &file_protos_parking_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Garage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Garage) ProtoMessage() {}

func (x *Garage) ProtoReflect() protoreflect.Message {
	mi := &file_protos_parking_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Garage.ProtoReflect.Descriptor instead.
func (*Garage) Descriptor() ([]byte, []int) {
	return file_protos_parking_service_proto_rawDescGZIP(), []int{3}
}

func (x *Garage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Garage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Garage) GetBasePrice() float64 {
	if x != nil {
		return x.BasePrice
	}
	return 0
}

func (x *Garage) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Garage) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Garage) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Garage) GetCampaigns() []*Campaign {
	if x != nil {
		return x.Campaigns
	}
	return nil
}

func (x *Garage) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Garage) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Garage) GetTotalSpots() int32 {
	if x != nil {
		return x.TotalSpots
	}
	return 0
}

func (x *Garage) GetAvailableSpots() int32 {
	if x != nil {
		return x.AvailableSpots
	}
	return 0
}

func (x *Garage) GetAmenities() []string {
	if x != nil {
		return x.Amenities
	}
	return nil
}

type Campaign struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartnerName   string                 `protobuf:"bytes,1,opt,name=partner_name,json=partnerName,proto3" json:"partner_name,omitempty"`
	DiscountRule  string                 `protobuf:"bytes,2,opt,name=discount_rule,json=discountRule,proto3" json:"discount_rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Campaign) Reset() {
	*x = Campaign{}
	mi := &file_protos_parking_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Campaign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Campaign) ProtoMessage() {}

func (x *Campaign) ProtoReflect() protoreflect.Message {
	mi := &file_protos_parking_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Campaign.ProtoReflect.Descriptor instead.
func (*Campaign) Descriptor() ([]byte, []int) {
	return file_protos_parking_service_proto_rawDescGZIP(), []int{4}
}

func (x *Campaign) GetPartnerName() string {
	if x != nil {
		return x.PartnerName
	}
	return ""
}

func (x *Campaign) GetDiscountRule() string {
	if x != nil {
		return x.DiscountRule
	}
	return ""
}

type CreateReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GarageId      string                 `protobuf:"bytes,2,opt,name=garage_id,json=garageId,proto3" json:"garage_id,omitempty"`
	StartTime     int64                  `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // Unix timestamp (segundos)
	EndTime       int64                  `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // Unix timestamp (segundos)
	VehiclePlate  string                 `protobuf:"bytes,5,opt,name=vehicle_plate,json=vehiclePlate,proto3" json:"vehicle_plate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReservationRequest) Reset() {
	*x = CreateReservationRequest{}
	mi := &file_protos_parking_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReservationRequest) ProtoMessage() {}

func (x *CreateReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_parking_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReservationRequest.ProtoReflect.Descriptor instead.
func (*CreateReservationRequest) Descriptor() ([]byte, []int) {
	return file_protos_parking_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateReservationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateReservationRequest) GetGarageId() string {
	if x != nil {
		return x.GarageId
	}
	return ""
}

func (x *CreateReservationRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *CreateReservationRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *CreateReservationRequest) GetVehiclePlate() string {
	if x != nil {
		return x.VehiclePlate
	}
	return ""
}

type Reservation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GarageId      string                 `protobuf:"bytes,3,opt,name=garage_id,json=garageId,proto3" json:"garage_id,omitempty"`
	GarageName    string                 `protobuf:"bytes,4,opt,name=garage_name,json=garageName,proto3" json:"garage_name,omitempty"`
	StartTime     int64                  `protobuf:"varint,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	VehiclePlate  string                 `protobuf:"bytes,7,opt,name=vehicle_plate,json=vehiclePlate,proto3" json:"vehicle_plate,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,8,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	Status        ReservationStatus      `protobuf:"varint,9,opt,name=status,proto3,enum=parking.ReservationStatus" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reservation) Reset() {
	*x = Reservation{}
	mi := &file_protos_parking_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reservation) ProtoMessage() {}

func (x *Reservation) ProtoReflect() protoreflect.Message {
	mi := &file_protos_parking_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reservation.ProtoReflect.Descriptor instead.
func (*Reservation) Descriptor() ([]byte, []int) {
	return file_protos_parking_service_proto_rawDescGZIP(), []int{6}
}

func (x *Reservation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Reservation) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Reservation) GetGarageId() string {
	if x != nil {
		return x.GarageId
	}
	return ""
}

func (x *Reservation) GetGarageName() string {
	if x != nil {
		return x.GarageName
	}
	return ""
}

func (x *Reservation) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Reservation) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *Reservation) GetVehiclePlate() string {
	if x != nil {
		return x.VehiclePlate
	}
	return ""
}

func (x *Reservation) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *Reservation) GetStatus() ReservationStatus {
	if x != nil {
		return x.Status
	}
	return ReservationStatus_RESERVATION_STATUS_UNSPECIFIED
}

func (x *Reservation) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListReservationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StatusFilter  ReservationStatus      `protobuf:"varint,2,opt,name=status_filter,json=statusFilter,proto3,enum=parking.ReservationStatus" json:"status_filter,omitempty"` // Opcional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReservationsRequest) Reset() {
	*x = ListReservationsRequest{}
	mi := &file_protos_parking_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReservationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReservationsRequest) ProtoMessage() {}

func (x *ListReservationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_parking_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReservationsRequest.ProtoReflect.Descriptor instead.
func (*ListReservationsRequest) Descriptor() ([]byte, []int) {
	return file_protos_parking_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListReservationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListReservationsRequest) GetStatusFilter() ReservationStatus {
	if x != nil {
		return x.StatusFilter
	}
	return ReservationStatus_RESERVATION_STATUS_UNSPECIFIED
}

type ListReservationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reservations  []*Reservation         `protobuf:"bytes,1,rep,name=reservations,proto3" json:"reservations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReservationsResponse) Reset() {
	*x = ListReservationsResponse{}
	mi := &file_protos_parking_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReservationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReservationsResponse) ProtoMessage() {}

func (x *ListReservationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_parking_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReservationsResponse.ProtoReflect.Descriptor instead.
func (*ListReservationsResponse) Descriptor() ([]byte, []int) {
	return file_protos_parking_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListReservationsResponse) GetReservations() []*Reservation {
	if x != nil {
		return x.Reservations
	}
	return nil
}

type CancelReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Para validação de ownership
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelReservationRequest) Reset() {
	*x = CancelReservationRequest{}
	mi := &file_protos_parking_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelReservationRequest) ProtoMessage() {}

func (x *CancelReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_parking_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelReservationRequest.ProtoReflect.Descriptor instead.
func (*CancelReservationRequest) Descriptor() ([]byte, []int) {
	return file_protos_parking_service_proto_rawDescGZIP(), []int{9}
}

func (x *CancelReservationRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *CancelReservationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CancelReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelReservationResponse) Reset() {
	*x = CancelReservationResponse{}
	mi := &file_protos_parking_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelReservationResponse) ProtoMessage() {}

func (x *CancelReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_parking_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelReservationResponse.ProtoReflect.Descriptor instead.
func (*CancelReservationResponse) Descriptor() ([]byte, []int) {
	return file_protos_parking_service_proto_rawDescGZIP(), []int{10}
}

func (x *CancelReservationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelReservationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type VehicleEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GarageId      string                 `protobuf:"bytes,1,opt,name=garage_id,json=garageId,proto3" json:"garage_id,omitempty"`
	VehiclePlate  string                 `protobuf:"bytes,2,opt,name=vehicle_plate,json=vehiclePlate,proto3" json:"vehicle_plate,omitempty"`
	EntryTime     int64                  `protobuf:"varint,3,opt,name=entry_time,json=entryTime,proto3" json:"entry_time,omitempty"` // Unix timestamp (segundos)
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`           // Opcional: ID do usuário (se vinculado a reserva)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleEntryRequest) Reset() {
	*x = VehicleEntryRequest{}
	mi := &file_protos_parking_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleEntryRequest) ProtoMessage() {}

func (x *VehicleEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_parking_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleEntryRequest.ProtoReflect.Descriptor instead.
func (*VehicleEntryRequest) Descriptor() ([]byte, []int) {
	return file_protos_parking_service_proto_rawDescGZIP(), []int{11}
}

func (x *VehicleEntryRequest) GetGarageId() string {
	if x != nil {
		return x.GarageId
	}
	return ""
}

func (x *VehicleEntryRequest) GetVehiclePlate() string {
	if x != nil {
		return x.VehiclePlate
	}
	return ""
}

func (x *VehicleEntryRequest) GetEntryTime() int64 {
	if x != nil {
		return x.EntryTime
	}
	return 0
}

func (x *VehicleEntryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type VehicleEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntryId       string                 `protobuf:"bytes,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"` // ID único da entrada (garage_id|plate)
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	EntryTime     int64                  `protobuf:"varint,4,opt,name=entry_time,json=entryTime,proto3" json:"entry_time,omitempty"` // Timestamp da entrada registrada
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleEntryResponse) Reset() {
	*x = VehicleEntryResponse{}
	mi := &file_protos_parking_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleEntryResponse) ProtoMessage() {}

func (x *VehicleEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_parking_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleEntryResponse.ProtoReflect.Descriptor instead.
func (*VehicleEntryResponse) Descriptor() ([]byte, []int) {
	return file_protos_parking_service_proto_rawDescGZIP(), []int{12}
}

func (x *VehicleEntryResponse) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

func (x *VehicleEntryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VehicleEntryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VehicleEntryResponse) GetEntryTime() int64 {
	if x != nil {
		return x.EntryTime
	}
	return 0
}

type VehicleExitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GarageId      string                 `protobuf:"bytes,1,opt,name=garage_id,json=garageId,proto3" json:"garage_id,omitempty"`
	VehiclePlate  string                 `protobuf:"bytes,2,opt,name=vehicle_plate,json=vehiclePlate,proto3" json:"vehicle_plate,omitempty"`
	ExitTime      int64                  `protobuf:"varint,3,opt,name=exit_time,json=exitTime,proto3" json:"exit_time,omitempty"` // Unix timestamp (segundos)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleExitRequest) Reset() {
	*x = VehicleExitRequest{}
	mi := &file_protos_parking_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleExitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleExitRequest) ProtoMessage() {}

func (x *VehicleExitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_parking_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleExitRequest.ProtoReflect.Descriptor instead.
func (*VehicleExitRequest) Descriptor() ([]byte, []int) {
	return file_protos_parking_service_proto_rawDescGZIP(), []int{13}
}

func (x *VehicleExitRequest) GetGarageId() string {
	if x != nil {
		return x.GarageId
	}
	return ""
}

func (x *VehicleExitRequest) GetVehiclePlate() string {
	if x != nil {
		return x.VehiclePlate
	}
	return ""
}

func (x *VehicleExitRequest) GetExitTime() int64 {
	if x != nil {
		return x.ExitTime
	}
	return 0
}

type VehicleExitResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EntryId         string                 `protobuf:"bytes,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	TotalAmount     float64                `protobuf:"fixed64,2,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`            // Valor total a pagar
	DurationSeconds int64                  `protobuf:"varint,3,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"` // Tempo de permanência
	EntryTime       int64                  `protobuf:"varint,4,opt,name=entry_time,json=entryTime,proto3" json:"entry_time,omitempty"`                   // Quando entrou
	ExitTime        int64                  `protobuf:"varint,5,opt,name=exit_time,json=exitTime,proto3" json:"exit_time,omitempty"`                      // Quando saiu
	Success         bool                   `protobuf:"varint,6,opt,name=success,proto3" json:"success,omitempty"`
	Message         string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VehicleExitResponse) Reset() {
	*x = VehicleExitResponse{}
	mi := &file_protos_parking_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleExitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleExitResponse) ProtoMessage() {}

func (x *VehicleExitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_parking_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleExitResponse.ProtoReflect.Descriptor instead.
func (*VehicleExitResponse) Descriptor() ([]byte, []int) {
	return file_protos_parking_service_proto_rawDescGZIP(), []int{14}
}

func (x *VehicleExitResponse) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

func (x *VehicleExitResponse) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *VehicleExitResponse) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *VehicleExitResponse) GetEntryTime() int64 {
	if x != nil {
		return x.EntryTime
	}
	return 0
}

func (x *VehicleExitResponse) GetExitTime() int64 {
	if x != nil {
		return x.ExitTime
	}
	return 0
}

func (x *VehicleExitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VehicleExitResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type VehicleEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Chave composta: garage_id|vehicle_plate
	GarageId      string                 `protobuf:"bytes,2,opt,name=garage_id,json=garageId,proto3" json:"garage_id,omitempty"`
	VehiclePlate  string                 `protobuf:"bytes,3,opt,name=vehicle_plate,json=vehiclePlate,proto3" json:"vehicle_plate,omitempty"`
	EntryTime     int64                  `protobuf:"varint,4,opt,name=entry_time,json=entryTime,proto3" json:"entry_time,omitempty"`
	ExitTime      int64                  `protobuf:"varint,5,opt,name=exit_time,json=exitTime,proto3" json:"exit_time,omitempty"` // 0 se ainda estacionado
	AmountPaid    float64                `protobuf:"fixed64,6,opt,name=amount_paid,json=amountPaid,proto3" json:"amount_paid,omitempty"`
	Status        VehicleStatus          `protobuf:"varint,7,opt,name=status,proto3,enum=parking.VehicleStatus" json:"status,omitempty"`
	UserId        string                 `protobuf:"bytes,8,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Opcional: vinculado a reserva
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleEntry) Reset() {
	*x = VehicleEntry{}
	mi := &file_protos_parking_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleEntry) ProtoMessage() {}

func (x *VehicleEntry) ProtoReflect() protoreflect.Message {
	mi := &file_protos_parking_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleEntry.ProtoReflect.Descriptor instead.
func (*VehicleEntry) Descriptor() ([]byte, []int) {
	return file_protos_parking_service_proto_rawDescGZIP(), []int{15}
}

func (x *VehicleEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VehicleEntry) GetGarageId() string {
	if x != nil {
		return x.GarageId
	}
	return ""
}

func (x *VehicleEntry) GetVehiclePlate() string {
	if x != nil {
		return x.VehiclePlate
	}
	return ""
}

func (x *VehicleEntry) GetEntryTime() int64 {
	if x != nil {
		return x.EntryTime
	}
	return 0
}

func (x *VehicleEntry) GetExitTime() int64 {
	if x != nil {
		return x.ExitTime
	}
	return 0
}

func (x *VehicleEntry) GetAmountPaid() float64 {
	if x != nil {
		return x.AmountPaid
	}
	return 0
}

func (x *VehicleEntry) GetStatus() VehicleStatus {
	if x != nil {
		return x.Status
	}
	return VehicleStatus_VEHICLE_STATUS_UNSPECIFIED
}

func (x *VehicleEntry) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetActiveVehiclesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GarageId      string                 `protobuf:"bytes,1,opt,name=garage_id,json=garageId,proto3" json:"garage_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveVehiclesRequest) Reset() {
	*x = GetActiveVehiclesRequest{}
	mi := &file_protos_parking_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveVehiclesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveVehiclesRequest) ProtoMessage() {}

func (x *GetActiveVehiclesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_parking_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveVehiclesRequest.ProtoReflect.Descriptor instead.
func (*GetActiveVehiclesRequest) Descriptor() ([]byte, []int) {
	return file_protos_parking_service_proto_rawDescGZIP(), []int{16}
}

func (x *GetActiveVehiclesRequest) GetGarageId() string {
	if x != nil {
		return x.GarageId
	}
	return ""
}

type GetActiveVehiclesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vehicles      []*VehicleEntry        `protobuf:"bytes,1,rep,name=vehicles,proto3" json:"vehicles,omitempty"`
	TotalActive   int32                  `protobuf:"varint,2,opt,name=total_active,json=totalActive,proto3" json:"total_active,omitempty"` // Total de veículos atualmente estacionados
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveVehiclesResponse) Reset() {
	*x = GetActiveVehiclesResponse{}
	mi := &file_protos_parking_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveVehiclesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveVehiclesResponse) ProtoMessage() {}

func (x *GetActiveVehiclesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_parking_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveVehiclesResponse.ProtoReflect.Descriptor instead.
func (*GetActiveVehiclesResponse) Descriptor() ([]byte, []int) {
	return file_protos_parking_service_proto_rawDescGZIP(), []int{17}
}

func (x *GetActiveVehiclesResponse) GetVehicles() []*VehicleEntry {
	if x != nil {
		return x.Vehicles
	}
	return nil
}

func (x *GetActiveVehiclesResponse) GetTotalActive() int32 {
	if x != nil {
		return x.TotalActive
	}
	return 0
}

type GetVehicleEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GarageId      string                 `protobuf:"bytes,1,opt,name=garage_id,json=garageId,proto3" json:"garage_id,omitempty"`
	VehiclePlate  string                 `protobuf:"bytes,2,opt,name=vehicle_plate,json=vehiclePlate,proto3" json:"vehicle_plate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVehicleEntryRequest) Reset() {
	*x = GetVehicleEntryRequest{}
	mi := &file_protos_parking_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVehicleEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVehicleEntryRequest) ProtoMessage() {}

func (x *GetVehicleEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_parking_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVehicleEntryRequest.ProtoReflect.Descriptor instead.
func (*GetVehicleEntryRequest) Descriptor() ([]byte, []int) {
	return file_protos_parking_service_proto_rawDescGZIP(), []int{18}
}

func (x *GetVehicleEntryRequest) GetGarageId() string {
	if x != nil {
		return x.GarageId
	}
	return ""
}

func (x *GetVehicleEntryRequest) GetVehiclePlate() string {
	if x != nil {
		return x.VehiclePlate
	}
	return ""
}

var File_protos_parking_service_proto protoreflect.FileDescriptor

const file_protos_parking_service_proto_rawDesc = "" +
	"\n" +
	"\x1cprotos/parking_service.proto\x12\aparking\"n\n" +
	"\rSearchRequest\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12#\n" +
	"\rradius_meters\x18\x03 \x01(\x05R\fradiusMeters\";\n" +
	"\x0eSearchResponse\x12)\n" +
	"\agarages\x18\x01 \x03(\v2\x0f.parking.GarageR\agarages\"/\n" +
	"\x10GetGarageRequest\x12\x1b\n" +
	"\tgarage_id\x18\x01 \x01(\tR\bgarageId\"\xeb\x02\n" +
	"\x06Garage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"base_price\x18\x03 \x01(\x01R\tbasePrice\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x01R\tlongitude\x12\x1b\n" +
	"\timage_url\x18\x06 \x01(\tR\bimageUrl\x12/\n" +
	"\tcampaigns\x18\a \x03(\v2\x11.parking.CampaignR\tcampaigns\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\x12\x14\n" +
	"\x05phone\x18\t \x01(\tR\x05phone\x12\x1f\n" +
	"\vtotal_spots\x18\n" +
	" \x01(\x05R\n" +
	"totalSpots\x12'\n" +
	"\x0favailable_spots\x18\v \x01(\x05R\x0eavailableSpots\x12\x1c\n" +
	"\tamenities\x18\f \x03(\tR\tamenities\"R\n" +
	"\bCampaign\x12!\n" +
	"\fpartner_name\x18\x01 \x01(\tR\vpartnerName\x12#\n" +
	"\rdiscount_rule\x18\x02 \x01(\tR\fdiscountRule\"\xaf\x01\n" +
	"\x18CreateReservationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tgarage_id\x18\x02 \x01(\tR\bgarageId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\x03R\aendTime\x12#\n" +
	"\rvehicle_plate\x18\x05 \x01(\tR\fvehiclePlate\"\xc7\x02\n" +
	"\vReservation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tgarage_id\x18\x03 \x01(\tR\bgarageId\x12\x1f\n" +
	"\vgarage_name\x18\x04 \x01(\tR\n" +
	"garageName\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\x03R\aendTime\x12#\n" +
	"\rvehicle_plate\x18\a \x01(\tR\fvehiclePlate\x12\x1f\n" +
	"\vtotal_price\x18\b \x01(\x01R\n" +
	"totalPrice\x122\n" +
	"\x06status\x18\t \x01(\x0e2\x1a.parking.ReservationStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\"s\n" +
	"\x17ListReservationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12?\n" +
	"\rstatus_filter\x18\x02 \x01(\x0e2\x1a.parking.ReservationStatusR\fstatusFilter\"T\n" +
	"\x18ListReservationsResponse\x128\n" +
	"\freservations\x18\x01 \x03(\v2\x14.parking.ReservationR\freservations\"Z\n" +
	"\x18CancelReservationRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"O\n" +
	"\x19CancelReservationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x8f\x01\n" +
	"\x13VehicleEntryRequest\x12\x1b\n" +
	"\tgarage_id\x18\x01 \x01(\tR\bgarageId\x12#\n" +
	"\rvehicle_plate\x18\x02 \x01(\tR\fvehiclePlate\x12\x1d\n" +
	"\n" +
	"entry_time\x18\x03 \x01(\x03R\tentryTime\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\"\x84\x01\n" +
	"\x14VehicleEntryResponse\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\tR\aentryId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"entry_time\x18\x04 \x01(\x03R\tentryTime\"s\n" +
	"\x12VehicleExitRequest\x12\x1b\n" +
	"\tgarage_id\x18\x01 \x01(\tR\bgarageId\x12#\n" +
	"\rvehicle_plate\x18\x02 \x01(\tR\fvehiclePlate\x12\x1b\n" +
	"\texit_time\x18\x03 \x01(\x03R\bexitTime\"\xee\x01\n" +
	"\x13VehicleExitResponse\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\tR\aentryId\x12!\n" +
	"\ftotal_amount\x18\x02 \x01(\x01R\vtotalAmount\x12)\n" +
	"\x10duration_seconds\x18\x03 \x01(\x03R\x0fdurationSeconds\x12\x1d\n" +
	"\n" +
	"entry_time\x18\x04 \x01(\x03R\tentryTime\x12\x1b\n" +
	"\texit_time\x18\x05 \x01(\x03R\bexitTime\x12\x18\n" +
	"\asuccess\x18\x06 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\"\x86\x02\n" +
	"\fVehicleEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tgarage_id\x18\x02 \x01(\tR\bgarageId\x12#\n" +
	"\rvehicle_plate\x18\x03 \x01(\tR\fvehiclePlate\x12\x1d\n" +
	"\n" +
	"entry_time\x18\x04 \x01(\x03R\tentryTime\x12\x1b\n" +
	"\texit_time\x18\x05 \x01(\x03R\bexitTime\x12\x1f\n" +
	"\vamount_paid\x18\x06 \x01(\x01R\n" +
	"amountPaid\x12.\n" +
	"\x06status\x18\a \x01(\x0e2\x16.parking.VehicleStatusR\x06status\x12\x17\n" +
	"\auser_id\x18\b \x01(\tR\x06userId\"7\n" +
	"\x18GetActiveVehiclesRequest\x12\x1b\n" +
	"\tgarage_id\x18\x01 \x01(\tR\bgarageId\"q\n" +
	"\x19GetActiveVehiclesResponse\x121\n" +
	"\bvehicles\x18\x01 \x03(\v2\x15.parking.VehicleEntryR\bvehicles\x12!\n" +
	"\ftotal_active\x18\x02 \x01(\x05R\vtotalActive\"Z\n" +
	"\x16GetVehicleEntryRequest\x12\x1b\n" +
	"\tgarage_id\x18\x01 \x01(\tR\bgarageId\x12#\n" +
	"\rvehicle_plate\x18\x02 \x01(\tR\fvehiclePlate*n\n" +
	"\x11ReservationStatus\x12\"\n" +
	"\x1eRESERVATION_STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x02\x12\r\n" +
	"\tCOMPLETED\x10\x03\x12\r\n" +
	"\tCANCELLED\x10\x04*G\n" +
	"\rVehicleStatus\x12\x1e\n" +
	"\x1aVEHICLE_STATUS_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06PARKED\x10\x01\x12\n" +
	"\n" +
	"\x06EXITED\x10\x022\xd8\x05\n" +
	"\x0eParkingService\x12@\n" +
	"\rSearchGarages\x12\x16.parking.SearchRequest\x1a\x17.parking.SearchResponse\x127\n" +
	"\tGetGarage\x12\x19.parking.GetGarageRequest\x1a\x0f.parking.Garage\x12L\n" +
	"\x11CreateReservation\x12!.parking.CreateReservationRequest\x1a\x14.parking.Reservation\x12W\n" +
	"\x10ListReservations\x12 .parking.ListReservationsRequest\x1a!.parking.ListReservationsResponse\x12Z\n" +
	"\x11CancelReservation\x12!.parking.CancelReservationRequest\x1a\".parking.CancelReservationResponse\x12Q\n" +
	"\x12RecordVehicleEntry\x12\x1c.parking.VehicleEntryRequest\x1a\x1d.parking.VehicleEntryResponse\x12N\n" +
	"\x11RecordVehicleExit\x12\x1b.parking.VehicleExitRequest\x1a\x1c.parking.VehicleExitResponse\x12Z\n" +
	"\x11GetActiveVehicles\x12!.parking.GetActiveVehiclesRequest\x1a\".parking.GetActiveVehiclesResponse\x12I\n" +
	"\x0fGetVehicleEntry\x12\x1f.parking.GetVehicleEntryRequest\x1a\x15.parking.VehicleEntryB/Z-github.com/emersonnjsantos/ParkingZero/pkg/pbb\x06proto3"

var (
	file_protos_parking_service_proto_rawDescOnce sync.Once
	file_protos_parking_service_proto_rawDescData []byte
)

func file_protos_parking_service_proto_rawDescGZIP() []byte {
	file_protos_parking_service_proto_rawDescOnce.Do(func() {
		file_protos_parking_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_parking_service_proto_rawDesc), len(file_protos_parking_service_proto_rawDesc)))
	})
	return file_protos_parking_service_proto_rawDescData
}

var file_protos_parking_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protos_parking_service_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_protos_parking_service_proto_goTypes = []any{
	(ReservationStatus)(0),            // 0: parking.ReservationStatus
	(VehicleStatus)(0),                // 1: parking.VehicleStatus
	(*SearchRequest)(nil),             // 2: parking.SearchRequest
	(*SearchResponse)(nil),            // 3: parking.SearchResponse
	(*GetGarageRequest)(nil),          // 4: parking.GetGarageRequest
	(*Garage)(nil),                    // 5: parking.Garage
	(*Campaign)(nil),                  // 6: parking.Campaign
	(*CreateReservationRequest)(nil),  // 7: parking.CreateReservationRequest
	(*Reservation)(nil),               // 8: parking.Reservation
	(*ListReservationsRequest)(nil),   // 9: parking.ListReservationsRequest
	(*ListReservationsResponse)(nil),  // 10: parking.ListReservationsResponse
	(*CancelReservationRequest)(nil),  // 11: parking.CancelReservationRequest
	(*CancelReservationResponse)(nil), // 12: parking.CancelReservationResponse
	(*VehicleEntryRequest)(nil),       // 13: parking.VehicleEntryRequest
	(*VehicleEntryResponse)(nil),      // 14: parking.VehicleEntryResponse
	(*VehicleExitRequest)(nil),        // 15: parking.VehicleExitRequest
	(*VehicleExitResponse)(nil),       // 16: parking.VehicleExitResponse
	(*VehicleEntry)(nil),              // 17: parking.VehicleEntry
	(*GetActiveVehiclesRequest)(nil),  // 18: parking.GetActiveVehiclesRequest
	(*GetActiveVehiclesResponse)(nil), // 19: parking.GetActiveVehiclesResponse
	(*GetVehicleEntryRequest)(nil),    // 20: parking.GetVehicleEntryRequest
}
var file_protos_parking_service_proto_depIdxs = []int32{
	5,  // 0: parking.SearchResponse.garages:type_name -> parking.Garage
	6,  // 1: parking.Garage.campaigns:type_name -> parking.Campaign
	0,  // 2: parking.Reservation.status:type_name -> parking.ReservationStatus
	0,  // 3: parking.ListReservationsRequest.status_filter:type_name -> parking.ReservationStatus
	8,  // 4: parking.ListReservationsResponse.reservations:type_name -> parking.Reservation
	1,  // 5: parking.VehicleEntry.status:type_name -> parking.VehicleStatus
	17, // 6: parking.GetActiveVehiclesResponse.vehicles:type_name -> parking.VehicleEntry
	2,  // 7: parking.ParkingService.SearchGarages:input_type -> parking.SearchRequest
	4,  // 8: parking.ParkingService.GetGarage:input_type -> parking.GetGarageRequest
	7,  // 9: parking.ParkingService.CreateReservation:input_type -> parking.CreateReservationRequest
	9,  // 10: parking.ParkingService.ListReservations:input_type -> parking.ListReservationsRequest
	11, // 11: parking.ParkingService.CancelReservation:input_type -> parking.CancelReservationRequest
	13, // 12: parking.ParkingService.RecordVehicleEntry:input_type -> parking.VehicleEntryRequest
	15, // 13: parking.ParkingService.RecordVehicleExit:input_type -> parking.VehicleExitRequest
	18, // 14: parking.ParkingService.GetActiveVehicles:input_type -> parking.GetActiveVehiclesRequest
	20, // 15: parking.ParkingService.GetVehicleEntry:input_type -> parking.GetVehicleEntryRequest
	3,  // 16: parking.ParkingService.SearchGarages:output_type -> parking.SearchResponse
	5,  // 17: parking.ParkingService.GetGarage:output_type -> parking.Garage
	8,  // 18: parking.ParkingService.CreateReservation:output_type -> parking.Reservation
	10, // 19: parking.ParkingService.ListReservations:output_type -> parking.ListReservationsResponse
	12, // 20: parking.ParkingService.CancelReservation:output_type -> parking.CancelReservationResponse
	14, // 21: parking.ParkingService.RecordVehicleEntry:output_type -> parking.VehicleEntryResponse
	16, // 22: parking.ParkingService.RecordVehicleExit:output_type -> parking.VehicleExitResponse
	19, // 23: parking.ParkingService.GetActiveVehicles:output_type -> parking.GetActiveVehiclesResponse
	17, // 24: parking.ParkingService.GetVehicleEntry:output_type -> parking.VehicleEntry
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_protos_parking_service_proto_init() }
func file_protos_parking_service_proto_init() {
	if File_protos_parking_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_parking_service_proto_rawDesc), len(file_protos_parking_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_parking_service_proto_goTypes,
		DependencyIndexes: file_protos_parking_service_proto_depIdxs,
		EnumInfos:         file_protos_parking_service_proto_enumTypes,
		MessageInfos:      file_protos_parking_service_proto_msgTypes,
	}.Build()
	File_protos_parking_service_proto = out.File
	file_protos_parking_service_proto_goTypes = nil
	file_protos_parking_service_proto_depIdxs = nil
}
