// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_34zLVySbtGY0Un6Ud4AkW9wa13T1vPQ',
    appId: '1:621130922343:web:849ac8e9a9c6bab56017c2',
    messagingSenderId: '621130922343',
    projectId: 'parkingzero-app',
    authDomain: 'parkingzero-app.firebaseapp.com',
    storageBucket: 'parkingzero-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR-rEIAhH1Dq_JOAArwIIfT0DwKiapG2Q',
    appId: '1:621130922343:android:4080928f87bd90996017c2',
    messagingSenderId: '621130922343',
    projectId: 'parkingzero-app',
    storageBucket: 'parkingzero-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAToEGrkj8Pf9kxQvdT-SiRu5CR0iESKSE',
    appId: '1:621130922343:ios:e6b6d7cc4df47b186017c2',
    messagingSenderId: '621130922343',
    projectId: 'parkingzero-app',
    storageBucket: 'parkingzero-app.firebasestorage.app',
    iosBundleId: 'com.fronteira.parking.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAToEGrkj8Pf9kxQvdT-SiRu5CR0iESKSE',
    appId: '1:621130922343:ios:e6b6d7cc4df47b186017c2',
    messagingSenderId: '621130922343',
    projectId: 'parkingzero-app',
    storageBucket: 'parkingzero-app.firebasestorage.app',
    iosBundleId: 'com.fronteira.parking.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_34zLVySbtGY0Un6Ud4AkW9wa13T1vPQ',
    appId: '1:621130922343:web:c283c206404b58886017c2',
    messagingSenderId: '621130922343',
    projectId: 'parkingzero-app',
    authDomain: 'parkingzero-app.firebaseapp.com',
    storageBucket: 'parkingzero-app.firebasestorage.app',
  );

}